  name: Nuget Build 

  on: [push]

  jobs:
    nuget: 
      runs-on: macos-latest

      steps:

      - uses: actions/checkout@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GitHub" -source "https://nuget.pkg.github.com/thudugala/index.json" -userName thudugala -password ${{ secrets.Elvin_Package_Registry }}

      - name : restorePlugin.LocalNotification.sln
        run: nuget restore Source/Plugin.LocalNotification.sln

      - name: build Plugin.LocalNotification.csproj
        run: msbuild Source/Plugin.LocalNotification/Plugin.LocalNotification.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
      
      - uses: actions/upload-artifact@v1
        with:
          name: Plugin.LocalNotification
          path: Source/Plugin.LocalNotification/bin/Debug/ 

      - name: Push generated package to GitHub registry
        run: nuget push Source/Plugin.LocalNotification/bin/Debug/*.nupkg -Source "GitHub" -SkipDuplicate

